/**
 * Zod schemas for the four form templates.
 *
 * Field lists come from GRC_SaaS_Automation_Architecture.html. Required vs optional
 * follows the spec exactly, with one deliberate change: phone is optional on
 * quick_capture. GRC buyers routinely withhold a phone number on a first popup, and
 * the spec already says qualification happens on the sales call, not the form.
 *
 * Every schema is `passthrough()` — unknown keys survive into `raw_payload` so that
 * a field added to a form before the backend catches up is captured, not discarded.
 */
import { z } from 'zod';
import {
  COMPANY_SIZES,
  CountryCodeSchema,
  FRAMEWORKS,
  INQUIRY_TYPES,
  KNOWN_FORM_NAMES,
  SOLUTIONS,
  type FormId,
} from './enums.js';
import { HiddenFieldsSchema } from './hidden.js';

// ---------------------------------------------------------------------------
// Shared field builders
// ---------------------------------------------------------------------------

const email = z
  .string()
  .trim()
  .toLowerCase()
  .min(3)
  .max(255)
  .email('must be a valid email address');

const name = (max = 100) => z.string().trim().min(1).max(max);

/**
 * Loose on input, normalised later. E.164 conversion happens in the enrich job —
 * rejecting "+91 98765 43210" for its spaces loses a real lead over formatting.
 */
const phone = z
  .string()
  .trim()
  .min(6, 'phone number is too short')
  .max(32)
  .regex(/^[\d\s+()\-.]+$/, 'phone number contains invalid characters');

const company = z.string().trim().min(1).max(200);

/** Consent, as captured by the checkbox. The IP and timestamp are added server-side. */
const consent = z.object({
  consent_given: z.coerce.boolean().default(false),
  consent_text_version: z.string().max(50).optional(),
});

/**
 * Envelope present on every submission regardless of template.
 * `submission_uuid` is the idempotency key — a retry or double-click replays the
 * original response instead of creating a second lead.
 */
const envelope = z.object({
  submission_uuid: z.string().uuid('must be a v4 UUID generated by the client'),
  form_name: z
    .string()
    .trim()
    .min(1)
    .max(100)
    .default(KNOWN_FORM_NAMES[0]),
});

const base = envelope.merge(consent).merge(HiddenFieldsSchema);

// ---------------------------------------------------------------------------
// 01 — quick_capture
// Placed as the homepage popup and the solutions banner.
// CTA: "Talk to an expert". Qualify on the call, not on the form.
// ---------------------------------------------------------------------------
export const QuickCaptureSchema = base
  .extend({
    full_name: name(200),
    email,
    // Optional by deliberate deviation from the spec — see file header.
    phone: phone.optional(),
    company_name: company,
  })
  .passthrough();

// ---------------------------------------------------------------------------
// 02 — footer_form
// Site-wide passive capture. Lowest-commitment entry point in the system.
// Enters nurture, never the sales pipeline. CTA: "Get GRC insights".
// ---------------------------------------------------------------------------
export const FooterFormSchema = base
  .extend({
    email,
    full_name: name(200).optional(),
  })
  .passthrough();

// ---------------------------------------------------------------------------
// 03 — demo_form
// Highest-intent form. The visitor has committed, so more data is fair to ask for.
// `framework_interest` is added beyond the spec: Layer 2 nurture branches on
// framework, and the spec's only source for it was AI-parsing the free-text box.
// ---------------------------------------------------------------------------
export const DemoFormSchema = base
  .extend({
    first_name: name(100),
    last_name: name(100),
    email,
    phone,
    company_name: company,
    job_title: z.string().trim().min(1).max(150),
    company_size: z.enum(COMPANY_SIZES),

    // Asked explicitly rather than derived from the IP. GRC is jurisdiction-specific,
    // and a corporate VPN routinely reports the wrong country.
    country: CountryCodeSchema,

    // Which product area. This changes what the demo actually covers, so the rep
    // needs it before the call rather than discovering it in the first five minutes.
    solution_interest: z.array(z.enum(SOLUTIONS)).min(1).max(4),

    framework_interest: z.array(z.enum(FRAMEWORKS)).max(10).optional(),
    message: z.string().trim().max(5000).optional(),
  })
  .passthrough();

// ---------------------------------------------------------------------------
// 04 — contact_form
// General inquiry with routing. `inquiry_type` decides which team receives it and,
// for support/partnership/media, bypasses lead scoring entirely.
// ---------------------------------------------------------------------------
export const ContactFormSchema = base
  .extend({
    first_name: name(100),
    last_name: name(100),
    email,
    phone,
    company_name: company,
    job_title: z.string().trim().min(1).max(150).optional(),
    // Optional here: a support ticket or a press enquiry does not need a country,
    // and requiring it would add friction to a form people use when something is
    // already wrong.
    country: CountryCodeSchema.optional(),
    inquiry_type: z.enum(INQUIRY_TYPES),
    message: z.string().trim().min(1, 'message is required').max(5000),
  })
  .passthrough();

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const FORM_SCHEMAS = {
  quick_capture: QuickCaptureSchema,
  footer_form: FooterFormSchema,
  demo_form: DemoFormSchema,
  contact_form: ContactFormSchema,
} as const satisfies Record<FormId, z.ZodTypeAny>;

export type QuickCaptureInput = z.infer<typeof QuickCaptureSchema>;
export type FooterFormInput = z.infer<typeof FooterFormSchema>;
export type DemoFormInput = z.infer<typeof DemoFormSchema>;
export type ContactFormInput = z.infer<typeof ContactFormSchema>;

/** Union of every validated form payload. */
export type AnyFormInput =
  | QuickCaptureInput
  | FooterFormInput
  | DemoFormInput
  | ContactFormInput;

/**
 * Normalised shape the persistence layer works with, so it never has to branch on
 * which template produced the submission.
 */
export interface NormalisedSubmission {
  email: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  companyName?: string;
  jobTitle?: string;
  companySize?: string;
  frameworkInterest?: string[];
  solutionInterest?: string[];
  countryCode?: string;
  inquiryType?: string;
  message?: string;
  consentGiven: boolean;
  consentTextVersion?: string;
}

/** Split "Jane Q. Doe" into first and last. Everything after the first token is the surname. */
function splitFullName(full: string): { firstName: string; lastName?: string } {
  const parts = full.trim().split(/\s+/);
  const firstName = parts[0] ?? full.trim();
  const lastName = parts.length > 1 ? parts.slice(1).join(' ') : undefined;
  return lastName ? { firstName, lastName } : { firstName };
}

/**
 * Flatten any template's payload into one shape.
 *
 * quick_capture and footer_form collect a single `full_name`; demo_form and
 * contact_form collect first and last separately. This is the only place that
 * difference is handled.
 */
export function normalise(_formId: FormId, data: AnyFormInput): NormalisedSubmission {
  const d = data as Record<string, unknown>;

  let firstName: string | undefined;
  let lastName: string | undefined;

  if (typeof d.full_name === 'string' && d.full_name.trim()) {
    ({ firstName, lastName } = splitFullName(d.full_name));
  } else {
    firstName = typeof d.first_name === 'string' ? d.first_name : undefined;
    lastName = typeof d.last_name === 'string' ? d.last_name : undefined;
  }

  const str = (k: string): string | undefined =>
    typeof d[k] === 'string' && (d[k] as string).length > 0 ? (d[k] as string) : undefined;

  return {
    email: d.email as string,
    firstName,
    lastName,
    phone: str('phone'),
    companyName: str('company_name'),
    jobTitle: str('job_title'),
    companySize: str('company_size'),
    frameworkInterest: Array.isArray(d.framework_interest)
      ? (d.framework_interest as string[])
      : undefined,
    solutionInterest: Array.isArray(d.solution_interest)
      ? (d.solution_interest as string[])
      : undefined,
    countryCode: str('country'),
    inquiryType: str('inquiry_type'),
    message: str('message'),
    consentGiven: d.consent_given === true,
    consentTextVersion: str('consent_text_version'),
  };
}

/** Templates that must reject free email providers. Newsletter signup is exempt. */
export function requiresBusinessEmail(formId: FormId): boolean {
  return formId !== 'footer_form';
}
